title: "Devaprise Blog"
author: "VirusKA"
description: "Really cool blog about ... Devaprise"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://devaprise.com"
baseurl: "/blog" # comment out if in root directory

comments:
    disqus: "devaprise"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/Devaprise"
  - twitter: "https://twitter.com/Devaprise"
  - google-plus: "https://plus.google.com/+DevapriseCorp"
  - reddit: "https://www.reddit.com/user/Viruska"
  #- youtube: "https://www.youtube.com/user/me"
  #- steam: "http://steamcommunity.com/id/me/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
